[package]
name = "othello_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wait-timeout = "0.2.0"
nannou = "0.18.1"
num-derive = "0.3.0"
num-traits = "0.2.0"
rand = "0.8.5"
